/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronIngestRouteImport } from './routes/api/public/cron/ingest'
import { Route as ApiPublicCronDailyBriefRouteImport } from './routes/api/public/cron/daily-brief'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronIngestRoute = ApiPublicCronIngestRouteImport.update({
  id: '/api/public/cron/ingest',
  path: '/api/public/cron/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyBriefRoute = ApiPublicCronDailyBriefRouteImport.update({
  id: '/api/public/cron/daily-brief',
  path: '/api/public/cron/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/daily-brief': typeof ApiPublicCronDailyBriefRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/daily-brief': typeof ApiPublicCronDailyBriefRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/daily-brief': typeof ApiPublicCronDailyBriefRoute
  '/api/public/cron/ingest': typeof ApiPublicCronIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cron/daily-brief' | '/api/public/cron/ingest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cron/daily-brief' | '/api/public/cron/ingest'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/daily-brief'
    | '/api/public/cron/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronDailyBriefRoute: typeof ApiPublicCronDailyBriefRoute
  ApiPublicCronIngestRoute: typeof ApiPublicCronIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ingest': {
      id: '/api/public/cron/ingest'
      path: '/api/public/cron/ingest'
      fullPath: '/api/public/cron/ingest'
      preLoaderRoute: typeof ApiPublicCronIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-brief': {
      id: '/api/public/cron/daily-brief'
      path: '/api/public/cron/daily-brief'
      fullPath: '/api/public/cron/daily-brief'
      preLoaderRoute: typeof ApiPublicCronDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronDailyBriefRoute: ApiPublicCronDailyBriefRoute,
  ApiPublicCronIngestRoute: ApiPublicCronIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
